jenkins_master:
  build: .
  container_name: jk-master
  dockerfile: Dockerfile.jenkins  
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes_from:
    - jenkins_data
jenkins_data:
  build: .
  container_name: jk-data
  dockerfile: Dockerfile.data
  volumes:
    - /var/jenkins_home
    - /var/log/enkins
    - /var/cache/jenkins